on: push
name: Build & Release
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: platformio run
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: firmware_esp32.bin
        path: .pio/build/esp32/firmware_esp32.bin

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - .pio/build/esp32/firmware_esp32.bin
        - .pio/build/esp32/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
