on: push
name: Build & Release
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO
      run: platformio run

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: firmware_esp32.bin
        path: .pio/build/esp32/firmware_esp32.bin

    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: .pio/build/esp32/firmware_esp32.bin
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
